modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-only"
clientSideOnly=true
issueTrackerURL="https://github.com/decce6/Ixeris/issues"

[[mods]]
modId = "ixeris"
version = "${version}"
displayName = "Ixeris"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ixeris"
authors = "decce"
description = '''
Off-thread event polling
'''
logoFile = "assets/ixeris/icon.png"

[[dependencies.ixeris]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ixeris]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
